{{- if not .Values.secrets.externalSecret.name -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bastio.secretName" . }}
  labels:
    {{- include "bastio.labels" . | nindent 4 }}
type: Opaque
stringData:
  # Required.
  DATABASE_URL: {{ .Values.secrets.databaseURL | quote }}
  REDIS_URL: {{ .Values.secrets.redisURL | quote }}
  {{- if .Values.secrets.clickhouseURL }}
  CLICKHOUSE_URL: {{ .Values.secrets.clickhouseURL | quote }}
  {{- end }}
  {{- if .Values.secrets.openaiAPIKey }}
  OPENAI_API_KEY: {{ .Values.secrets.openaiAPIKey | quote }}
  {{- end }}
  {{- if .Values.secrets.anthropicAPIKey }}
  ANTHROPIC_API_KEY: {{ .Values.secrets.anthropicAPIKey | quote }}
  {{- end }}
{{- end -}}
