// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_keys.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO gateway_api_keys (customer_id, name, key_hash, key_prefix, scopes, rate_limit_rpm)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, customer_id, name, key_prefix, scopes, rate_limit_rpm, expires_at, last_used_at, is_active, created_at
`

type CreateAPIKeyParams struct {
	CustomerID   uuid.UUID   `json:"customer_id"`
	Name         string      `json:"name"`
	KeyHash      string      `json:"key_hash"`
	KeyPrefix    string      `json:"key_prefix"`
	Scopes       []string    `json:"scopes"`
	RateLimitRpm pgtype.Int4 `json:"rate_limit_rpm"`
}

type CreateAPIKeyRow struct {
	ID           uuid.UUID          `json:"id"`
	CustomerID   uuid.UUID          `json:"customer_id"`
	Name         string             `json:"name"`
	KeyPrefix    string             `json:"key_prefix"`
	Scopes       []string           `json:"scopes"`
	RateLimitRpm pgtype.Int4        `json:"rate_limit_rpm"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt   pgtype.Timestamptz `json:"last_used_at"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    time.Time          `json:"created_at"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (CreateAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.CustomerID,
		arg.Name,
		arg.KeyHash,
		arg.KeyPrefix,
		arg.Scopes,
		arg.RateLimitRpm,
	)
	var i CreateAPIKeyRow
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Name,
		&i.KeyPrefix,
		&i.Scopes,
		&i.RateLimitRpm,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT id, customer_id, name, key_prefix, scopes, rate_limit_rpm, expires_at, last_used_at, is_active, created_at
FROM gateway_api_keys
WHERE key_hash = $1 AND is_active = true
`

type GetAPIKeyByHashRow struct {
	ID           uuid.UUID          `json:"id"`
	CustomerID   uuid.UUID          `json:"customer_id"`
	Name         string             `json:"name"`
	KeyPrefix    string             `json:"key_prefix"`
	Scopes       []string           `json:"scopes"`
	RateLimitRpm pgtype.Int4        `json:"rate_limit_rpm"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt   pgtype.Timestamptz `json:"last_used_at"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    time.Time          `json:"created_at"`
}

func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (GetAPIKeyByHashRow, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByHash, keyHash)
	var i GetAPIKeyByHashRow
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Name,
		&i.KeyPrefix,
		&i.Scopes,
		&i.RateLimitRpm,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listAPIKeysByCustomer = `-- name: ListAPIKeysByCustomer :many
SELECT id, customer_id, name, key_prefix, scopes, rate_limit_rpm, expires_at, last_used_at, is_active, created_at
FROM gateway_api_keys
WHERE customer_id = $1
ORDER BY created_at DESC
`

type ListAPIKeysByCustomerRow struct {
	ID           uuid.UUID          `json:"id"`
	CustomerID   uuid.UUID          `json:"customer_id"`
	Name         string             `json:"name"`
	KeyPrefix    string             `json:"key_prefix"`
	Scopes       []string           `json:"scopes"`
	RateLimitRpm pgtype.Int4        `json:"rate_limit_rpm"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt   pgtype.Timestamptz `json:"last_used_at"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    time.Time          `json:"created_at"`
}

func (q *Queries) ListAPIKeysByCustomer(ctx context.Context, customerID uuid.UUID) ([]ListAPIKeysByCustomerRow, error) {
	rows, err := q.db.Query(ctx, listAPIKeysByCustomer, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAPIKeysByCustomerRow{}
	for rows.Next() {
		var i ListAPIKeysByCustomerRow
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.Name,
			&i.KeyPrefix,
			&i.Scopes,
			&i.RateLimitRpm,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :exec
UPDATE gateway_api_keys SET is_active = false WHERE id = $1 AND customer_id = $2
`

type RevokeAPIKeyParams struct {
	ID         uuid.UUID `json:"id"`
	CustomerID uuid.UUID `json:"customer_id"`
}

func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) error {
	_, err := q.db.Exec(ctx, revokeAPIKey, arg.ID, arg.CustomerID)
	return err
}

const updateAPIKeyLastUsed = `-- name: UpdateAPIKeyLastUsed :exec
UPDATE gateway_api_keys SET last_used_at = now() WHERE id = $1
`

func (q *Queries) UpdateAPIKeyLastUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateAPIKeyLastUsed, id)
	return err
}
