// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customers.sql

package dbgen

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (name, slug, settings)
VALUES ($1, $2, $3)
RETURNING id, name, slug, settings, created_at, updated_at
`

type CreateCustomerParams struct {
	Name     string          `json:"name"`
	Slug     string          `json:"slug"`
	Settings json.RawMessage `json:"settings"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, createCustomer, arg.Name, arg.Slug, arg.Settings)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomer = `-- name: GetCustomer :one
SELECT id, name, slug, settings, created_at, updated_at
FROM customers
WHERE id = $1
`

func (q *Queries) GetCustomer(ctx context.Context, id uuid.UUID) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomer, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerBySlug = `-- name: GetCustomerBySlug :one
SELECT id, name, slug, settings, created_at, updated_at
FROM customers
WHERE slug = $1
`

func (q *Queries) GetCustomerBySlug(ctx context.Context, slug string) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerBySlug, slug)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCustomers = `-- name: ListCustomers :many
SELECT id, name, slug, settings, created_at, updated_at
FROM customers
ORDER BY created_at DESC
`

func (q *Queries) ListCustomers(ctx context.Context) ([]Customer, error) {
	rows, err := q.db.Query(ctx, listCustomers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Customer{}
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Settings,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
