// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Customer struct {
	ID        uuid.UUID       `json:"id"`
	Name      string          `json:"name"`
	Slug      string          `json:"slug"`
	Settings  json.RawMessage `json:"settings"`
	CreatedAt time.Time       `json:"created_at"`
	UpdatedAt time.Time       `json:"updated_at"`
}

type GatewayApiKey struct {
	ID           uuid.UUID          `json:"id"`
	CustomerID   uuid.UUID          `json:"customer_id"`
	Name         string             `json:"name"`
	KeyHash      string             `json:"key_hash"`
	KeyPrefix    string             `json:"key_prefix"`
	Scopes       []string           `json:"scopes"`
	RateLimitRpm pgtype.Int4        `json:"rate_limit_rpm"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt   pgtype.Timestamptz `json:"last_used_at"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    time.Time          `json:"created_at"`
}

type ModelRoutingRule struct {
	ID         uuid.UUID `json:"id"`
	ProxyID    uuid.UUID `json:"proxy_id"`
	Priority   int32     `json:"priority"`
	Provider   string    `json:"provider"`
	Model      string    `json:"model"`
	Weight     int32     `json:"weight"`
	IsFallback bool      `json:"is_fallback"`
	IsActive   bool      `json:"is_active"`
	CreatedAt  time.Time `json:"created_at"`
}

type Prompt struct {
	ID          uuid.UUID `json:"id"`
	CustomerID  uuid.UUID `json:"customer_id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type PromptVersion struct {
	ID            uuid.UUID       `json:"id"`
	PromptID      uuid.UUID       `json:"prompt_id"`
	CustomerID    uuid.UUID       `json:"customer_id"`
	Version       int32           `json:"version"`
	Content       string          `json:"content"`
	ContentType   string          `json:"content_type"`
	Config        json.RawMessage `json:"config"`
	Labels        []string        `json:"labels"`
	CommitMessage string          `json:"commit_message"`
	CreatedBy     string          `json:"created_by"`
	CreatedAt     time.Time       `json:"created_at"`
}

type ProviderHealth struct {
	ID           uuid.UUID     `json:"id"`
	Provider     string        `json:"provider"`
	Model        string        `json:"model"`
	Status       string        `json:"status"`
	LastCheckAt  time.Time     `json:"last_check_at"`
	LatencyP50Ms pgtype.Int4   `json:"latency_p50_ms"`
	LatencyP95Ms pgtype.Int4   `json:"latency_p95_ms"`
	ErrorRate    pgtype.Float4 `json:"error_rate"`
	UpdatedAt    time.Time     `json:"updated_at"`
}

type Proxy struct {
	ID             uuid.UUID       `json:"id"`
	CustomerID     uuid.UUID       `json:"customer_id"`
	Name           string          `json:"name"`
	Slug           string          `json:"slug"`
	ListenPath     string          `json:"listen_path"`
	TargetProvider string          `json:"target_provider"`
	TargetModel    string          `json:"target_model"`
	Settings       json.RawMessage `json:"settings"`
	IsActive       bool            `json:"is_active"`
	CreatedAt      time.Time       `json:"created_at"`
	UpdatedAt      time.Time       `json:"updated_at"`
}

type ProxyProviderKey struct {
	ID           uuid.UUID       `json:"id"`
	CustomerID   uuid.UUID       `json:"customer_id"`
	ProxyID      pgtype.UUID     `json:"proxy_id"`
	Provider     string          `json:"provider"`
	EncryptedKey json.RawMessage `json:"encrypted_key"`
	IsDefault    bool            `json:"is_default"`
	CreatedAt    time.Time       `json:"created_at"`
	UpdatedAt    time.Time       `json:"updated_at"`
}

type RateLimitRule struct {
	ID            uuid.UUID   `json:"id"`
	CustomerID    uuid.UUID   `json:"customer_id"`
	ProxyID       pgtype.UUID `json:"proxy_id"`
	Name          string      `json:"name"`
	WindowSeconds int32       `json:"window_seconds"`
	MaxRequests   int32       `json:"max_requests"`
	MaxTokens     pgtype.Int4 `json:"max_tokens"`
	Scope         string      `json:"scope"`
	Action        string      `json:"action"`
	IsActive      bool        `json:"is_active"`
	CreatedAt     time.Time   `json:"created_at"`
}

type SecurityAccessRule struct {
	ID         uuid.UUID   `json:"id"`
	CustomerID uuid.UUID   `json:"customer_id"`
	ProfileID  pgtype.UUID `json:"profile_id"`
	RuleType   string      `json:"rule_type"`
	Value      string      `json:"value"`
	IsActive   bool        `json:"is_active"`
	CreatedAt  time.Time   `json:"created_at"`
}

type SecurityPattern struct {
	ID          uuid.UUID `json:"id"`
	CustomerID  uuid.UUID `json:"customer_id"`
	ProfileID   uuid.UUID `json:"profile_id"`
	Name        string    `json:"name"`
	PatternType string    `json:"pattern_type"`
	Pattern     string    `json:"pattern"`
	Action      string    `json:"action"`
	Severity    string    `json:"severity"`
	IsActive    bool      `json:"is_active"`
	CreatedAt   time.Time `json:"created_at"`
}

type SecurityProfile struct {
	ID                 uuid.UUID   `json:"id"`
	CustomerID         uuid.UUID   `json:"customer_id"`
	ProxyID            pgtype.UUID `json:"proxy_id"`
	Name               string      `json:"name"`
	InjectionEnabled   bool        `json:"injection_enabled"`
	InjectionThreshold float32     `json:"injection_threshold"`
	PiiEnabled         bool        `json:"pii_enabled"`
	// How to handle detected PII: mask (lossy) | tokenize (reversible) | block | warn | log_only
	PiiAction             string    `json:"pii_action"`
	JailbreakEnabled      bool      `json:"jailbreak_enabled"`
	JailbreakThreshold    float32   `json:"jailbreak_threshold"`
	BotDetectionEnabled   bool      `json:"bot_detection_enabled"`
	CustomPatternsEnabled bool      `json:"custom_patterns_enabled"`
	CreatedAt             time.Time `json:"created_at"`
	UpdatedAt             time.Time `json:"updated_at"`
	// When true, also scan the LLM response for PII that was not in the request (hallucination / RAG leak).
	PiiScanResponse bool `json:"pii_scan_response"`
	// When true and pii_action=tokenize, swap placeholders back to originals before returning the response to the caller.
	PiiRestoreResponse bool `json:"pii_restore_response"`
	// Placeholder shape when pii_action=tokenize: angle (<PII_SSN_1>) or curly ({{PII_SSN_1}}).
	PiiTokenStyle string `json:"pii_token_style"`
}
