// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: prompts.sql

package dbgen

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const clearLabelOnOtherVersions = `-- name: ClearLabelOnOtherVersions :exec
UPDATE prompt_versions
SET labels = array_remove(labels, $3::text)
WHERE customer_id = $1 AND prompt_id = $2 AND version != $4
  AND $3 = ANY(labels)
`

type ClearLabelOnOtherVersionsParams struct {
	CustomerID uuid.UUID `json:"customer_id"`
	PromptID   uuid.UUID `json:"prompt_id"`
	Column3    string    `json:"column_3"`
	Version    int32     `json:"version"`
}

// Removes a given label from every version of a prompt except the one
// being promoted. Keeps deploy labels unique per prompt.
func (q *Queries) ClearLabelOnOtherVersions(ctx context.Context, arg ClearLabelOnOtherVersionsParams) error {
	_, err := q.db.Exec(ctx, clearLabelOnOtherVersions,
		arg.CustomerID,
		arg.PromptID,
		arg.Column3,
		arg.Version,
	)
	return err
}

const createPrompt = `-- name: CreatePrompt :one
INSERT INTO prompts (customer_id, name, description)
VALUES ($1, $2, $3)
RETURNING id, customer_id, name, description, created_at, updated_at
`

type CreatePromptParams struct {
	CustomerID  uuid.UUID `json:"customer_id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
}

func (q *Queries) CreatePrompt(ctx context.Context, arg CreatePromptParams) (Prompt, error) {
	row := q.db.QueryRow(ctx, createPrompt, arg.CustomerID, arg.Name, arg.Description)
	var i Prompt
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPromptVersion = `-- name: CreatePromptVersion :one
INSERT INTO prompt_versions (
    prompt_id, customer_id, version, content, content_type,
    config, labels, commit_message, created_by
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, prompt_id, customer_id, version, content, content_type,
          config, labels, commit_message, created_by, created_at
`

type CreatePromptVersionParams struct {
	PromptID      uuid.UUID       `json:"prompt_id"`
	CustomerID    uuid.UUID       `json:"customer_id"`
	Version       int32           `json:"version"`
	Content       string          `json:"content"`
	ContentType   string          `json:"content_type"`
	Config        json.RawMessage `json:"config"`
	Labels        []string        `json:"labels"`
	CommitMessage string          `json:"commit_message"`
	CreatedBy     string          `json:"created_by"`
}

func (q *Queries) CreatePromptVersion(ctx context.Context, arg CreatePromptVersionParams) (PromptVersion, error) {
	row := q.db.QueryRow(ctx, createPromptVersion,
		arg.PromptID,
		arg.CustomerID,
		arg.Version,
		arg.Content,
		arg.ContentType,
		arg.Config,
		arg.Labels,
		arg.CommitMessage,
		arg.CreatedBy,
	)
	var i PromptVersion
	err := row.Scan(
		&i.ID,
		&i.PromptID,
		&i.CustomerID,
		&i.Version,
		&i.Content,
		&i.ContentType,
		&i.Config,
		&i.Labels,
		&i.CommitMessage,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deletePrompt = `-- name: DeletePrompt :exec
DELETE FROM prompts p
WHERE p.id = $1 AND p.customer_id = $2
  AND NOT EXISTS (SELECT 1 FROM prompt_versions pv WHERE pv.prompt_id = p.id)
`

type DeletePromptParams struct {
	ID         uuid.UUID `json:"id"`
	CustomerID uuid.UUID `json:"customer_id"`
}

// Deletes only when no versions reference the prompt. Cascaded cleanup
// is handled explicitly in the handler so UI can warn the user first.
func (q *Queries) DeletePrompt(ctx context.Context, arg DeletePromptParams) error {
	_, err := q.db.Exec(ctx, deletePrompt, arg.ID, arg.CustomerID)
	return err
}

const getLatestPromptVersion = `-- name: GetLatestPromptVersion :one
SELECT id, prompt_id, customer_id, version, content, content_type,
       config, labels, commit_message, created_by, created_at
FROM prompt_versions
WHERE customer_id = $1 AND prompt_id = $2
ORDER BY version DESC
LIMIT 1
`

type GetLatestPromptVersionParams struct {
	CustomerID uuid.UUID `json:"customer_id"`
	PromptID   uuid.UUID `json:"prompt_id"`
}

func (q *Queries) GetLatestPromptVersion(ctx context.Context, arg GetLatestPromptVersionParams) (PromptVersion, error) {
	row := q.db.QueryRow(ctx, getLatestPromptVersion, arg.CustomerID, arg.PromptID)
	var i PromptVersion
	err := row.Scan(
		&i.ID,
		&i.PromptID,
		&i.CustomerID,
		&i.Version,
		&i.Content,
		&i.ContentType,
		&i.Config,
		&i.Labels,
		&i.CommitMessage,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getPromptByName = `-- name: GetPromptByName :one
SELECT id, customer_id, name, description, created_at, updated_at
FROM prompts
WHERE customer_id = $1 AND name = $2
`

type GetPromptByNameParams struct {
	CustomerID uuid.UUID `json:"customer_id"`
	Name       string    `json:"name"`
}

func (q *Queries) GetPromptByName(ctx context.Context, arg GetPromptByNameParams) (Prompt, error) {
	row := q.db.QueryRow(ctx, getPromptByName, arg.CustomerID, arg.Name)
	var i Prompt
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPromptVersion = `-- name: GetPromptVersion :one
SELECT id, prompt_id, customer_id, version, content, content_type,
       config, labels, commit_message, created_by, created_at
FROM prompt_versions
WHERE customer_id = $1 AND prompt_id = $2 AND version = $3
`

type GetPromptVersionParams struct {
	CustomerID uuid.UUID `json:"customer_id"`
	PromptID   uuid.UUID `json:"prompt_id"`
	Version    int32     `json:"version"`
}

func (q *Queries) GetPromptVersion(ctx context.Context, arg GetPromptVersionParams) (PromptVersion, error) {
	row := q.db.QueryRow(ctx, getPromptVersion, arg.CustomerID, arg.PromptID, arg.Version)
	var i PromptVersion
	err := row.Scan(
		&i.ID,
		&i.PromptID,
		&i.CustomerID,
		&i.Version,
		&i.Content,
		&i.ContentType,
		&i.Config,
		&i.Labels,
		&i.CommitMessage,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getPromptVersionByLabel = `-- name: GetPromptVersionByLabel :one
SELECT id, prompt_id, customer_id, version, content, content_type,
       config, labels, commit_message, created_by, created_at
FROM prompt_versions
WHERE customer_id = $1 AND prompt_id = $2 AND $3 = ANY(labels)
ORDER BY version DESC
LIMIT 1
`

type GetPromptVersionByLabelParams struct {
	CustomerID uuid.UUID `json:"customer_id"`
	PromptID   uuid.UUID `json:"prompt_id"`
	Labels     []string  `json:"labels"`
}

// Used by the SDK fetch endpoint when a caller asks for prompts/:name?label=production.
// Returns the newest version carrying the label (labels move with releases).
func (q *Queries) GetPromptVersionByLabel(ctx context.Context, arg GetPromptVersionByLabelParams) (PromptVersion, error) {
	row := q.db.QueryRow(ctx, getPromptVersionByLabel, arg.CustomerID, arg.PromptID, arg.Labels)
	var i PromptVersion
	err := row.Scan(
		&i.ID,
		&i.PromptID,
		&i.CustomerID,
		&i.Version,
		&i.Content,
		&i.ContentType,
		&i.Config,
		&i.Labels,
		&i.CommitMessage,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listPromptVersions = `-- name: ListPromptVersions :many
SELECT id, prompt_id, customer_id, version, content, content_type,
       config, labels, commit_message, created_by, created_at
FROM prompt_versions
WHERE customer_id = $1 AND prompt_id = $2
ORDER BY version DESC
`

type ListPromptVersionsParams struct {
	CustomerID uuid.UUID `json:"customer_id"`
	PromptID   uuid.UUID `json:"prompt_id"`
}

func (q *Queries) ListPromptVersions(ctx context.Context, arg ListPromptVersionsParams) ([]PromptVersion, error) {
	rows, err := q.db.Query(ctx, listPromptVersions, arg.CustomerID, arg.PromptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PromptVersion{}
	for rows.Next() {
		var i PromptVersion
		if err := rows.Scan(
			&i.ID,
			&i.PromptID,
			&i.CustomerID,
			&i.Version,
			&i.Content,
			&i.ContentType,
			&i.Config,
			&i.Labels,
			&i.CommitMessage,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrompts = `-- name: ListPrompts :many
SELECT
    p.id, p.customer_id, p.name, p.description, p.created_at, p.updated_at,
    v.version AS latest_version,
    v.content_type AS latest_content_type,
    v.labels AS latest_labels,
    v.created_at AS latest_created_at
FROM prompts p
LEFT JOIN LATERAL (
    SELECT version, content_type, labels, created_at
    FROM prompt_versions
    WHERE prompt_id = p.id
    ORDER BY version DESC
    LIMIT 1
) v ON TRUE
WHERE p.customer_id = $1
ORDER BY p.updated_at DESC
`

type ListPromptsRow struct {
	ID                uuid.UUID `json:"id"`
	CustomerID        uuid.UUID `json:"customer_id"`
	Name              string    `json:"name"`
	Description       string    `json:"description"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
	LatestVersion     int32     `json:"latest_version"`
	LatestContentType string    `json:"latest_content_type"`
	LatestLabels      []string  `json:"latest_labels"`
	LatestCreatedAt   time.Time `json:"latest_created_at"`
}

// Returns one row per prompt with its latest version metadata so the
// Prompts list page can render without N+1 queries.
func (q *Queries) ListPrompts(ctx context.Context, customerID uuid.UUID) ([]ListPromptsRow, error) {
	rows, err := q.db.Query(ctx, listPrompts, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPromptsRow{}
	for rows.Next() {
		var i ListPromptsRow
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LatestVersion,
			&i.LatestContentType,
			&i.LatestLabels,
			&i.LatestCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextPromptVersion = `-- name: NextPromptVersion :one
SELECT COALESCE(MAX(version), 0) + 1 AS next_version
FROM prompt_versions
WHERE prompt_id = $1
`

// Atomic next version number. Used inside the CreatePromptVersion txn.
func (q *Queries) NextPromptVersion(ctx context.Context, promptID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextPromptVersion, promptID)
	var next_version int32
	err := row.Scan(&next_version)
	return next_version, err
}

const setVersionLabels = `-- name: SetVersionLabels :one
UPDATE prompt_versions
SET labels = $4
WHERE customer_id = $1 AND prompt_id = $2 AND version = $3
RETURNING id, prompt_id, customer_id, version, content, content_type,
          config, labels, commit_message, created_by, created_at
`

type SetVersionLabelsParams struct {
	CustomerID uuid.UUID `json:"customer_id"`
	PromptID   uuid.UUID `json:"prompt_id"`
	Version    int32     `json:"version"`
	Labels     []string  `json:"labels"`
}

// Replaces the labels array on a specific version. "production" and similar
// deploy labels typically belong on exactly one version at a time; the
// handler enforces that semantic when writing.
func (q *Queries) SetVersionLabels(ctx context.Context, arg SetVersionLabelsParams) (PromptVersion, error) {
	row := q.db.QueryRow(ctx, setVersionLabels,
		arg.CustomerID,
		arg.PromptID,
		arg.Version,
		arg.Labels,
	)
	var i PromptVersion
	err := row.Scan(
		&i.ID,
		&i.PromptID,
		&i.CustomerID,
		&i.Version,
		&i.Content,
		&i.ContentType,
		&i.Config,
		&i.Labels,
		&i.CommitMessage,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const touchPrompt = `-- name: TouchPrompt :exec
UPDATE prompts SET updated_at = NOW() WHERE id = $1 AND customer_id = $2
`

type TouchPromptParams struct {
	ID         uuid.UUID `json:"id"`
	CustomerID uuid.UUID `json:"customer_id"`
}

func (q *Queries) TouchPrompt(ctx context.Context, arg TouchPromptParams) error {
	_, err := q.db.Exec(ctx, touchPrompt, arg.ID, arg.CustomerID)
	return err
}
