// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: provider_keys.sql

package dbgen

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProviderKey = `-- name: CreateProviderKey :one
INSERT INTO proxy_provider_keys (customer_id, proxy_id, provider, encrypted_key, is_default)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, customer_id, proxy_id, provider, encrypted_key, is_default, created_at, updated_at
`

type CreateProviderKeyParams struct {
	CustomerID   uuid.UUID       `json:"customer_id"`
	ProxyID      pgtype.UUID     `json:"proxy_id"`
	Provider     string          `json:"provider"`
	EncryptedKey json.RawMessage `json:"encrypted_key"`
	IsDefault    bool            `json:"is_default"`
}

func (q *Queries) CreateProviderKey(ctx context.Context, arg CreateProviderKeyParams) (ProxyProviderKey, error) {
	row := q.db.QueryRow(ctx, createProviderKey,
		arg.CustomerID,
		arg.ProxyID,
		arg.Provider,
		arg.EncryptedKey,
		arg.IsDefault,
	)
	var i ProxyProviderKey
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.ProxyID,
		&i.Provider,
		&i.EncryptedKey,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProviderKey = `-- name: GetProviderKey :one
SELECT id, customer_id, proxy_id, provider, encrypted_key, is_default, created_at, updated_at
FROM proxy_provider_keys
WHERE customer_id = $1 AND provider = $2
    AND (proxy_id = $3 OR (proxy_id IS NULL AND is_default = true))
ORDER BY proxy_id NULLS LAST
LIMIT 1
`

type GetProviderKeyParams struct {
	CustomerID uuid.UUID   `json:"customer_id"`
	Provider   string      `json:"provider"`
	ProxyID    pgtype.UUID `json:"proxy_id"`
}

func (q *Queries) GetProviderKey(ctx context.Context, arg GetProviderKeyParams) (ProxyProviderKey, error) {
	row := q.db.QueryRow(ctx, getProviderKey, arg.CustomerID, arg.Provider, arg.ProxyID)
	var i ProxyProviderKey
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.ProxyID,
		&i.Provider,
		&i.EncryptedKey,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProviderKeysByCustomer = `-- name: ListProviderKeysByCustomer :many
SELECT id, customer_id, proxy_id, provider, encrypted_key, is_default, created_at, updated_at
FROM proxy_provider_keys
WHERE customer_id = $1
ORDER BY provider, created_at DESC
`

func (q *Queries) ListProviderKeysByCustomer(ctx context.Context, customerID uuid.UUID) ([]ProxyProviderKey, error) {
	rows, err := q.db.Query(ctx, listProviderKeysByCustomer, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProxyProviderKey{}
	for rows.Next() {
		var i ProxyProviderKey
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.ProxyID,
			&i.Provider,
			&i.EncryptedKey,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
