// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: proxies.sql

package dbgen

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createProxy = `-- name: CreateProxy :one
INSERT INTO proxies (customer_id, name, slug, listen_path, target_provider, target_model, settings)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, customer_id, name, slug, listen_path, target_provider, target_model, settings, is_active, created_at, updated_at
`

type CreateProxyParams struct {
	CustomerID     uuid.UUID       `json:"customer_id"`
	Name           string          `json:"name"`
	Slug           string          `json:"slug"`
	ListenPath     string          `json:"listen_path"`
	TargetProvider string          `json:"target_provider"`
	TargetModel    string          `json:"target_model"`
	Settings       json.RawMessage `json:"settings"`
}

func (q *Queries) CreateProxy(ctx context.Context, arg CreateProxyParams) (Proxy, error) {
	row := q.db.QueryRow(ctx, createProxy,
		arg.CustomerID,
		arg.Name,
		arg.Slug,
		arg.ListenPath,
		arg.TargetProvider,
		arg.TargetModel,
		arg.Settings,
	)
	var i Proxy
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Name,
		&i.Slug,
		&i.ListenPath,
		&i.TargetProvider,
		&i.TargetModel,
		&i.Settings,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProxy = `-- name: DeleteProxy :exec
DELETE FROM proxies
WHERE id = $1 AND customer_id = $2
`

type DeleteProxyParams struct {
	ID         uuid.UUID `json:"id"`
	CustomerID uuid.UUID `json:"customer_id"`
}

func (q *Queries) DeleteProxy(ctx context.Context, arg DeleteProxyParams) error {
	_, err := q.db.Exec(ctx, deleteProxy, arg.ID, arg.CustomerID)
	return err
}

const getProxy = `-- name: GetProxy :one
SELECT id, customer_id, name, slug, listen_path, target_provider, target_model, settings, is_active, created_at, updated_at
FROM proxies
WHERE id = $1 AND customer_id = $2
`

type GetProxyParams struct {
	ID         uuid.UUID `json:"id"`
	CustomerID uuid.UUID `json:"customer_id"`
}

func (q *Queries) GetProxy(ctx context.Context, arg GetProxyParams) (Proxy, error) {
	row := q.db.QueryRow(ctx, getProxy, arg.ID, arg.CustomerID)
	var i Proxy
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Name,
		&i.Slug,
		&i.ListenPath,
		&i.TargetProvider,
		&i.TargetModel,
		&i.Settings,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProxiesByCustomer = `-- name: ListProxiesByCustomer :many
SELECT id, customer_id, name, slug, listen_path, target_provider, target_model, settings, is_active, created_at, updated_at
FROM proxies
WHERE customer_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListProxiesByCustomer(ctx context.Context, customerID uuid.UUID) ([]Proxy, error) {
	rows, err := q.db.Query(ctx, listProxiesByCustomer, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Proxy{}
	for rows.Next() {
		var i Proxy
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.Name,
			&i.Slug,
			&i.ListenPath,
			&i.TargetProvider,
			&i.TargetModel,
			&i.Settings,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProxy = `-- name: UpdateProxy :exec
UPDATE proxies
SET name = $3, target_provider = $4, target_model = $5, settings = $6, is_active = $7
WHERE id = $1 AND customer_id = $2
`

type UpdateProxyParams struct {
	ID             uuid.UUID       `json:"id"`
	CustomerID     uuid.UUID       `json:"customer_id"`
	Name           string          `json:"name"`
	TargetProvider string          `json:"target_provider"`
	TargetModel    string          `json:"target_model"`
	Settings       json.RawMessage `json:"settings"`
	IsActive       bool            `json:"is_active"`
}

func (q *Queries) UpdateProxy(ctx context.Context, arg UpdateProxyParams) error {
	_, err := q.db.Exec(ctx, updateProxy,
		arg.ID,
		arg.CustomerID,
		arg.Name,
		arg.TargetProvider,
		arg.TargetModel,
		arg.Settings,
		arg.IsActive,
	)
	return err
}
