// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: security_profiles.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSecurityProfile = `-- name: CreateSecurityProfile :one
INSERT INTO security_profiles (customer_id, proxy_id, name,
    injection_enabled, injection_threshold,
    pii_enabled, pii_action,
    pii_scan_response, pii_restore_response, pii_token_style,
    jailbreak_enabled, jailbreak_threshold,
    bot_detection_enabled, custom_patterns_enabled)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, customer_id, proxy_id, name,
    injection_enabled, injection_threshold,
    pii_enabled, pii_action,
    pii_scan_response, pii_restore_response, pii_token_style,
    jailbreak_enabled, jailbreak_threshold,
    bot_detection_enabled, custom_patterns_enabled,
    created_at, updated_at
`

type CreateSecurityProfileParams struct {
	CustomerID            uuid.UUID   `json:"customer_id"`
	ProxyID               pgtype.UUID `json:"proxy_id"`
	Name                  string      `json:"name"`
	InjectionEnabled      bool        `json:"injection_enabled"`
	InjectionThreshold    float32     `json:"injection_threshold"`
	PiiEnabled            bool        `json:"pii_enabled"`
	PiiAction             string      `json:"pii_action"`
	PiiScanResponse       bool        `json:"pii_scan_response"`
	PiiRestoreResponse    bool        `json:"pii_restore_response"`
	PiiTokenStyle         string      `json:"pii_token_style"`
	JailbreakEnabled      bool        `json:"jailbreak_enabled"`
	JailbreakThreshold    float32     `json:"jailbreak_threshold"`
	BotDetectionEnabled   bool        `json:"bot_detection_enabled"`
	CustomPatternsEnabled bool        `json:"custom_patterns_enabled"`
}

type CreateSecurityProfileRow struct {
	ID                    uuid.UUID   `json:"id"`
	CustomerID            uuid.UUID   `json:"customer_id"`
	ProxyID               pgtype.UUID `json:"proxy_id"`
	Name                  string      `json:"name"`
	InjectionEnabled      bool        `json:"injection_enabled"`
	InjectionThreshold    float32     `json:"injection_threshold"`
	PiiEnabled            bool        `json:"pii_enabled"`
	PiiAction             string      `json:"pii_action"`
	PiiScanResponse       bool        `json:"pii_scan_response"`
	PiiRestoreResponse    bool        `json:"pii_restore_response"`
	PiiTokenStyle         string      `json:"pii_token_style"`
	JailbreakEnabled      bool        `json:"jailbreak_enabled"`
	JailbreakThreshold    float32     `json:"jailbreak_threshold"`
	BotDetectionEnabled   bool        `json:"bot_detection_enabled"`
	CustomPatternsEnabled bool        `json:"custom_patterns_enabled"`
	CreatedAt             time.Time   `json:"created_at"`
	UpdatedAt             time.Time   `json:"updated_at"`
}

func (q *Queries) CreateSecurityProfile(ctx context.Context, arg CreateSecurityProfileParams) (CreateSecurityProfileRow, error) {
	row := q.db.QueryRow(ctx, createSecurityProfile,
		arg.CustomerID,
		arg.ProxyID,
		arg.Name,
		arg.InjectionEnabled,
		arg.InjectionThreshold,
		arg.PiiEnabled,
		arg.PiiAction,
		arg.PiiScanResponse,
		arg.PiiRestoreResponse,
		arg.PiiTokenStyle,
		arg.JailbreakEnabled,
		arg.JailbreakThreshold,
		arg.BotDetectionEnabled,
		arg.CustomPatternsEnabled,
	)
	var i CreateSecurityProfileRow
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.ProxyID,
		&i.Name,
		&i.InjectionEnabled,
		&i.InjectionThreshold,
		&i.PiiEnabled,
		&i.PiiAction,
		&i.PiiScanResponse,
		&i.PiiRestoreResponse,
		&i.PiiTokenStyle,
		&i.JailbreakEnabled,
		&i.JailbreakThreshold,
		&i.BotDetectionEnabled,
		&i.CustomPatternsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDefaultSecurityProfile = `-- name: GetDefaultSecurityProfile :one
SELECT id, customer_id, proxy_id, name,
    injection_enabled, injection_threshold,
    pii_enabled, pii_action,
    pii_scan_response, pii_restore_response, pii_token_style,
    jailbreak_enabled, jailbreak_threshold,
    bot_detection_enabled, custom_patterns_enabled,
    created_at, updated_at
FROM security_profiles
WHERE customer_id = $1 AND name = 'default'
LIMIT 1
`

type GetDefaultSecurityProfileRow struct {
	ID                    uuid.UUID   `json:"id"`
	CustomerID            uuid.UUID   `json:"customer_id"`
	ProxyID               pgtype.UUID `json:"proxy_id"`
	Name                  string      `json:"name"`
	InjectionEnabled      bool        `json:"injection_enabled"`
	InjectionThreshold    float32     `json:"injection_threshold"`
	PiiEnabled            bool        `json:"pii_enabled"`
	PiiAction             string      `json:"pii_action"`
	PiiScanResponse       bool        `json:"pii_scan_response"`
	PiiRestoreResponse    bool        `json:"pii_restore_response"`
	PiiTokenStyle         string      `json:"pii_token_style"`
	JailbreakEnabled      bool        `json:"jailbreak_enabled"`
	JailbreakThreshold    float32     `json:"jailbreak_threshold"`
	BotDetectionEnabled   bool        `json:"bot_detection_enabled"`
	CustomPatternsEnabled bool        `json:"custom_patterns_enabled"`
	CreatedAt             time.Time   `json:"created_at"`
	UpdatedAt             time.Time   `json:"updated_at"`
}

func (q *Queries) GetDefaultSecurityProfile(ctx context.Context, customerID uuid.UUID) (GetDefaultSecurityProfileRow, error) {
	row := q.db.QueryRow(ctx, getDefaultSecurityProfile, customerID)
	var i GetDefaultSecurityProfileRow
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.ProxyID,
		&i.Name,
		&i.InjectionEnabled,
		&i.InjectionThreshold,
		&i.PiiEnabled,
		&i.PiiAction,
		&i.PiiScanResponse,
		&i.PiiRestoreResponse,
		&i.PiiTokenStyle,
		&i.JailbreakEnabled,
		&i.JailbreakThreshold,
		&i.BotDetectionEnabled,
		&i.CustomPatternsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSecurityProfile = `-- name: GetSecurityProfile :one
SELECT id, customer_id, proxy_id, name,
    injection_enabled, injection_threshold,
    pii_enabled, pii_action,
    pii_scan_response, pii_restore_response, pii_token_style,
    jailbreak_enabled, jailbreak_threshold,
    bot_detection_enabled, custom_patterns_enabled,
    created_at, updated_at
FROM security_profiles
WHERE id = $1 AND customer_id = $2
`

type GetSecurityProfileParams struct {
	ID         uuid.UUID `json:"id"`
	CustomerID uuid.UUID `json:"customer_id"`
}

type GetSecurityProfileRow struct {
	ID                    uuid.UUID   `json:"id"`
	CustomerID            uuid.UUID   `json:"customer_id"`
	ProxyID               pgtype.UUID `json:"proxy_id"`
	Name                  string      `json:"name"`
	InjectionEnabled      bool        `json:"injection_enabled"`
	InjectionThreshold    float32     `json:"injection_threshold"`
	PiiEnabled            bool        `json:"pii_enabled"`
	PiiAction             string      `json:"pii_action"`
	PiiScanResponse       bool        `json:"pii_scan_response"`
	PiiRestoreResponse    bool        `json:"pii_restore_response"`
	PiiTokenStyle         string      `json:"pii_token_style"`
	JailbreakEnabled      bool        `json:"jailbreak_enabled"`
	JailbreakThreshold    float32     `json:"jailbreak_threshold"`
	BotDetectionEnabled   bool        `json:"bot_detection_enabled"`
	CustomPatternsEnabled bool        `json:"custom_patterns_enabled"`
	CreatedAt             time.Time   `json:"created_at"`
	UpdatedAt             time.Time   `json:"updated_at"`
}

func (q *Queries) GetSecurityProfile(ctx context.Context, arg GetSecurityProfileParams) (GetSecurityProfileRow, error) {
	row := q.db.QueryRow(ctx, getSecurityProfile, arg.ID, arg.CustomerID)
	var i GetSecurityProfileRow
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.ProxyID,
		&i.Name,
		&i.InjectionEnabled,
		&i.InjectionThreshold,
		&i.PiiEnabled,
		&i.PiiAction,
		&i.PiiScanResponse,
		&i.PiiRestoreResponse,
		&i.PiiTokenStyle,
		&i.JailbreakEnabled,
		&i.JailbreakThreshold,
		&i.BotDetectionEnabled,
		&i.CustomPatternsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSecurityProfilesByCustomer = `-- name: ListSecurityProfilesByCustomer :many
SELECT id, customer_id, proxy_id, name,
    injection_enabled, injection_threshold,
    pii_enabled, pii_action,
    pii_scan_response, pii_restore_response, pii_token_style,
    jailbreak_enabled, jailbreak_threshold,
    bot_detection_enabled, custom_patterns_enabled,
    created_at, updated_at
FROM security_profiles
WHERE customer_id = $1
ORDER BY created_at DESC
`

type ListSecurityProfilesByCustomerRow struct {
	ID                    uuid.UUID   `json:"id"`
	CustomerID            uuid.UUID   `json:"customer_id"`
	ProxyID               pgtype.UUID `json:"proxy_id"`
	Name                  string      `json:"name"`
	InjectionEnabled      bool        `json:"injection_enabled"`
	InjectionThreshold    float32     `json:"injection_threshold"`
	PiiEnabled            bool        `json:"pii_enabled"`
	PiiAction             string      `json:"pii_action"`
	PiiScanResponse       bool        `json:"pii_scan_response"`
	PiiRestoreResponse    bool        `json:"pii_restore_response"`
	PiiTokenStyle         string      `json:"pii_token_style"`
	JailbreakEnabled      bool        `json:"jailbreak_enabled"`
	JailbreakThreshold    float32     `json:"jailbreak_threshold"`
	BotDetectionEnabled   bool        `json:"bot_detection_enabled"`
	CustomPatternsEnabled bool        `json:"custom_patterns_enabled"`
	CreatedAt             time.Time   `json:"created_at"`
	UpdatedAt             time.Time   `json:"updated_at"`
}

func (q *Queries) ListSecurityProfilesByCustomer(ctx context.Context, customerID uuid.UUID) ([]ListSecurityProfilesByCustomerRow, error) {
	rows, err := q.db.Query(ctx, listSecurityProfilesByCustomer, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSecurityProfilesByCustomerRow{}
	for rows.Next() {
		var i ListSecurityProfilesByCustomerRow
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.ProxyID,
			&i.Name,
			&i.InjectionEnabled,
			&i.InjectionThreshold,
			&i.PiiEnabled,
			&i.PiiAction,
			&i.PiiScanResponse,
			&i.PiiRestoreResponse,
			&i.PiiTokenStyle,
			&i.JailbreakEnabled,
			&i.JailbreakThreshold,
			&i.BotDetectionEnabled,
			&i.CustomPatternsEnabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
